"use client";
import { useEffect, useMemo, useState } from "react";
import FeatureUniverse from "./feature-universe";

type Feature={name:string;group:string;icon:string};
export const FEATURES:Feature[]=[
 ...["Onboarding guidé","Recherche globale","Palette de commandes","Centre de notifications","Création de campagne","Création de client","Import de rushs","Filtres intelligents","Tri des données","Vues grille et liste"].map(name=>({name,group:"Pilotage",icon:"⌂"})),
 ...["Brief de campagne","Budget par campagne","Rémunération au CPM","Plafond par clip","Période de tracking","Règles de publication","Ciblage par plateforme","Statuts personnalisés","Duplicateur de campagne","Rapport partageable"].map(name=>({name,group:"Campagnes",icon:"◉"})),
 ...["Détection des moments forts","Générateur de hooks","Transcription automatique","Sous-titres dynamiques","Traduction multilingue","Score de viralité","Recadrage vertical","Suppression des silences","Nettoyage audio","Export SRT"].map(name=>({name,group:"Studio IA",icon:"✦"})),
 ...["Kanban de production","Assignation des monteurs","Deadlines","Commentaires horodatés","Validation client","Demandes de révision","Bibliothèque de templates","Brand kits","Bibliothèque de CTA","Gestion des versions"].map(name=>({name,group:"Production",icon:"▶"})),
 ...["Calendrier éditorial","Programmation TikTok","Programmation Instagram","Programmation YouTube","Programmation LinkedIn","File d’attente de publication","Meilleurs horaires","Prévisualisation mobile","Watermark automatique","Publication multicomptes"].map(name=>({name,group:"Diffusion",icon:"□"})),
 ...["Vues multiréseaux","Rétention moyenne","Comparaison de périodes","Top clips","Attribution des leads","Suivi des conversions","Revenus par contenu","Export PDF","Rapports automatiques","Liens de rapports publics"].map(name=>({name,group:"Analytics",icon:"↗"})),
 ...["Invitation d’équipe","Rôles et permissions","Charge de travail","Classement des clippeurs","Badges de performance","Objectifs individuels","Journal d’activité","Validation à plusieurs","Messagerie interne","Portail client"].map(name=>({name,group:"Équipe",icon:"♙"})),
 ...["Marketplace de clippeurs","Découverte de campagnes","Candidatures","Portfolio public","Score de fiabilité","Soumission de clips","Motifs de refus","Gestion des litiges","Programme de parrainage","Favoris et listes"].map(name=>({name,group:"Marketplace",icon:"◎"})),
 ...["Portefeuille agence","Factures clients","Paiements des clippeurs","Historique des transactions","Demandes de retrait","Calcul des marges","Prévisions de trésorerie","Coupons promotionnels","Plans d’abonnement","Exports comptables"].map(name=>({name,group:"Finance",icon:"€"})),
 ...["Automatisations no-code","Webhooks","Clés API","Connexion Google Drive","Connexion Dropbox","Connexion Discord","Connexion Slack","Mode marque blanche","Domaine personnalisé","Conformité et droits"].map(name=>({name,group:"Infrastructure",icon:"⚙"})),
];

const menu=[["Vue d’ensemble","⌂"],["Campagnes","◉"],["Studio IA","✦"],["Clips","▶"],["Calendrier","□"],["Équipe","♙"],["Clients","◇"],["Marketplace","◎"],["Finance","€"],["Analytics","↗"],["Automations","⌁"],["Intégrations","＋"],["Paramètres","⚙"]];
const baseCampaigns=[
 {name:"Nova Finance",initials:"NF",status:"Active",clips:24,views:"1.84M",budget:2760,progress:72,color:"violet"},
 {name:"Kinetik Podcast",initials:"KP",status:"Active",clips:18,views:"682K",budget:1023,progress:54,color:"cyan"},
 {name:"Maison Aura",initials:"MA",status:"Review",clips:12,views:"391K",budget:586,progress:38,color:"orange"},
 {name:"Scale Room",initials:"SR",status:"Brouillon",clips:0,views:"—",budget:1800,progress:12,color:"green"},
];
const clipData=[
 {title:"Le déclic qui a tout changé",client:"Nova Finance",views:"428K",retention:81,status:"Viral",score:94,tone:"purple"},
 {title:"3 erreurs qui coûtent cher",client:"Kinetik Podcast",views:"186K",retention:74,status:"Publié",score:86,tone:"blue"},
 {title:"Pourquoi personne ne vous le dit",client:"Maison Aura",views:"92K",retention:69,status:"Publié",score:79,tone:"amber"},
 {title:"La règle des 10 minutes",client:"Nova Finance",views:"61K",retention:72,status:"Validation",score:82,tone:"green"},
 {title:"Ce conseil vaut de l’or",client:"Kinetik Podcast",views:"—",retention:0,status:"Montage",score:88,tone:"pink"},
 {title:"J’aurais aimé savoir ça",client:"Maison Aura",views:"—",retention:0,status:"Brief",score:76,tone:"blue"},
];
const team=[["ML","Maya Laurent","Lead editor","12 clips","92%"],["NB","Nassim B.","Clipper","9 clips","88%"],["LC","Léo Chen","Monteur","7 clips","84%"],["SK","Sarah K.","Content manager","5 clips","96%"]];
const clients=[["NF","Nova Finance","contact@novafinance.fr","24 clips","1.84M"],["KP","Kinetik Podcast","hello@kinetik.fr","18 clips","682K"],["MA","Maison Aura","team@maisonaura.fr","12 clips","391K"],["SR","Scale Room","content@scaleroom.fr","0 clip","—"]];

function Mark(){return <span className="mark"><i/><i/><i/></span>}
function Badge({children,tone="green"}:{children:React.ReactNode;tone?:string}){return <span className={`app-badge ${tone}`}>{children}</span>}
function Empty({icon,title,text,action,onClick}:{icon:string;title:string;text:string;action:string;onClick:()=>void}){return <div className="empty-state"><span>{icon}</span><h3>{title}</h3><p>{text}</p><button className="accent-btn" onClick={onClick}>{action}</button></div>}

export default function ProductApp({exit}:{exit:()=>void}){
 const[section,setSection]=useState("Vue d’ensemble");const[toast,setToast]=useState("");const[modal,setModal]=useState("");const[search,setSearch]=useState("");const[compact,setCompact]=useState(false);const[mobile,setMobile]=useState(false);const[notifications,setNotifications]=useState(false);const[campaigns,setCampaigns]=useState(baseCampaigns);const[filter,setFilter]=useState("Toutes");const[range,setRange]=useState("30 jours");const[connected,setConnected]=useState<string[]>(["Google Drive"]);const[automations,setAutomations]=useState([true,true,false,true,false]);const[onboard,setOnboard]=useState(64);
 useEffect(()=>{const saved=localStorage.getItem("clipscale-section");if(saved)setSection(saved)},[]);
 useEffect(()=>localStorage.setItem("clipscale-section",section),[section]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)};
 const go=(x:string)=>{setSection(x);setMobile(false)};
 const results=useMemo(()=>search?FEATURES.filter(f=>f.name.toLowerCase().includes(search.toLowerCase())).slice(0,8):[],[search]);
 const filtered=filter==="Toutes"?campaigns:campaigns.filter(c=>c.status===filter);
 const connect=(name:string)=>{setConnected(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name]);notify(connected.includes(name)?`${name} déconnecté`:`${name} connecté`)};
 const createCampaign=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get("name")||"Nouvelle campagne");setCampaigns(v=>[...v,{name,initials:name.slice(0,2).toUpperCase(),status:"Brouillon",clips:0,views:"—",budget:Number(fd.get("budget"))||1000,progress:5,color:"violet"}]);setModal("");go("Campagnes");notify("Campagne créée et sauvegardée")};
 return <main className={`pro-app ${compact?"compact":""}`}>
  <aside className={`pro-sidebar ${mobile?"open":""}`}><button className="brand" onClick={exit}><Mark/>ClipScale</button><button className="workspace-switch"><b>AV</b><span><strong>Ventura Agency</strong><small>Agency Scale</small></span><i>⌄</i></button><div className="side-title">ESPACE DE TRAVAIL</div><nav>{menu.map(([name,icon])=><button key={name} className={section===name?"active":""} onClick={()=>go(name)}><i>{icon}</i>{name}{name==="Clips"&&<em>8</em>}</button>)}</nav><div className="side-progress"><div><span>Configuration</span><b>{onboard}%</b></div><i><b style={{width:`${onboard}%`}}/></i><p>Encore 3 étapes pour terminer.</p><button onClick={()=>setModal("tour")}>Continuer →</button></div><div className="pro-profile"><b>AV</b><span><strong>Aron Ventura</strong><small>Fondateur</small></span><button>•••</button></div></aside>
  <section className="pro-content"><header className="app-top"><button className="mobile-menu" onClick={()=>setMobile(v=>!v)}>☰</button><div><small>VENTURA AGENCY / {section.toUpperCase()}</small><h1>{section}</h1></div><div className="top-actions"><button className="search-btn" onClick={()=>setModal("search")}>⌕ <span>Rechercher...</span><kbd>⌘ K</kbd></button><button className="round-btn" onClick={()=>setNotifications(v=>!v)}>♢<i/></button><button className="accent-btn" onClick={()=>setModal("campaign")}>＋ Nouvelle campagne</button></div></header>
   {section==="Vue d’ensemble"&&<Overview setSection={go} setModal={setModal} range={range} setRange={setRange} onboard={onboard}/>}
   {section==="Campagnes"&&<Campaigns data={filtered} filter={filter} setFilter={setFilter} open={()=>setModal("campaign")} notify={notify}/>}
   {section==="Studio IA"&&<Studio notify={notify} openUpload={()=>setModal("upload")}/>}
   {section==="Clips"&&<Clips notify={notify}/>}
   {section==="Calendrier"&&<Calendar notify={notify}/>}
   {section==="Équipe"&&<Team notify={notify} invite={()=>setModal("invite")}/>}
   {section==="Clients"&&<Clients notify={notify} add={()=>setModal("client")}/>}
   {section==="Marketplace"&&<Marketplace notify={notify}/>}
   {section==="Finance"&&<Finance notify={notify}/>}
   {section==="Analytics"&&<Analytics range={range} setRange={setRange} notify={notify}/>}
   {section==="Automations"&&<Automations values={automations} setValues={setAutomations} notify={notify}/>}
   {section==="Intégrations"&&<Integrations connected={connected} connect={connect}/>}
   {section==="Paramètres"&&<Settings compact={compact} setCompact={setCompact} notify={notify} showFeatures={()=>setModal("features")}/>}
  </section>
  {notifications&&<div className="notification-drawer"><div className="drawer-head"><h3>Notifications</h3><button onClick={()=>setNotifications(false)}>×</button></div>{[["ML","Maya a soumis un nouveau clip","Il y a 4 min"],["↗","Nova Finance dépasse 1,8M vues","Il y a 28 min"],["€","Un paiement de 420 € est prêt","Il y a 1 h"],["✓","3 clips ont été approuvés","Hier"]].map(n=><article key={n[1]}><b>{n[0]}</b><span><strong>{n[1]}</strong><small>{n[2]}</small></span></article>)}<button className="drawer-link">Tout marquer comme lu</button></div>}
  {modal&&<Modal type={modal} close={()=>{setModal("");setSearch("")}} search={search} setSearch={setSearch} results={results} createCampaign={createCampaign} go={go} notify={notify} onboard={onboard} setOnboard={setOnboard}/>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}

function Overview({setSection,setModal,range,setRange,onboard}:{setSection:(x:string)=>void;setModal:(x:string)=>void;range:string;setRange:(x:string)=>void;onboard:number}){
 return <div className="app-page"><div className="welcome"><div><h2>Bonjour Aron <span>👋</span></h2><p>Votre agence a généré <b>218 400 vues</b> aujourd’hui.</p></div><div className="live-pill"><i/> Données synchronisées</div></div><div className="pro-metrics">{[["◉","VUES TOTALES","2.91M","↗ 24.8%"],["▶","CLIPS PUBLIÉS","142","↗ 18.2%"],["⌁","RÉTENTION MOY.","74.6%","↗ 6.4%"],["€","REVENUS GÉNÉRÉS","18 420 €","↗ 31.5%"]].map((m,i)=><article key={m[1]}><span className={`metric-symbol s${i}`}>{m[0]}</span><small>{m[1]}</small><strong>{m[2]}</strong><p>{m[3]} <span>vs. mois dernier</span></p></article>)}</div>
 <div className="overview-grid"><article className="app-card performance-card"><div className="app-card-head"><div><small>PERFORMANCE</small><h3>Vues générées</h3></div><select value={range} onChange={e=>setRange(e.target.value)}><option>7 jours</option><option>30 jours</option><option>90 jours</option></select></div><AreaChart/></article><article className="app-card"><div className="app-card-head"><div><small>RÉPARTITION</small><h3>Par plateforme</h3></div><button>•••</button></div>{[["♪","TikTok","1.64M",56],["◎","Instagram","824K",28],["▶","YouTube Shorts","446K",16]].map((p,i)=><div className="platform-row" key={p[1]}><b className={`platform-icon p${i}`}>{p[0]}</b><span><strong>{p[1]}</strong><i><b style={{width:`${p[3]}%`}}/></i></span><em>{p[2]}<small>{p[3]}%</small></em></div>)}</article></div>
 <div className="overview-bottom"><article className="app-card"><div className="app-card-head"><div><small>PIPELINE</small><h3>Production en cours</h3></div><button onClick={()=>setSection("Clips")}>Tout afficher →</button></div><div className="pipeline">{[["Brief","8","purple"],["Montage","12","blue"],["Validation","5","amber"],["Planifié","18","green"]].map(p=><button key={p[0]} onClick={()=>setSection("Clips")}><i className={p[2]}/><span><b>{p[1]}</b><small>{p[0]}</small></span><em>→</em></button>)}</div></article><article className="app-card quick-card"><div className="app-card-head"><div><small>ACTIONS RAPIDES</small><h3>Créer et avancer</h3></div></div><div className="quick-grid"><button onClick={()=>setModal("upload")}>⇧<span>Importer un rush</span></button><button onClick={()=>setModal("client")}>◇<span>Ajouter un client</span></button><button onClick={()=>setModal("invite")}>♙<span>Inviter un membre</span></button><button onClick={()=>setSection("Analytics")}>↗<span>Créer un rapport</span></button></div></article></div>
 <div className="app-card campaign-preview"><div className="app-card-head"><div><small>CAMPAGNES</small><h3>Campagnes actives</h3></div><button onClick={()=>setSection("Campagnes")}>Voir toutes →</button></div>{baseCampaigns.slice(0,3).map(c=><div className="campaign-line" key={c.name}><b className={c.color}>{c.initials}</b><span><strong>{c.name}</strong><small>Campagne Août</small></span><Badge tone={c.status==="Review"?"amber":"green"}>{c.status}</Badge><em>{c.clips} clips</em><strong>{c.views}</strong><div className="mini-progress"><i style={{width:`${c.progress}%`}}/></div><button>•••</button></div>)}</div></div>
}

function AreaChart(){return <div className="area-chart"><div className="axis-labels"><span>300K</span><span>200K</span><span>100K</span><span>0</span></div><div className="chart-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#866cff" stopOpacity=".38"/><stop offset="1" stopColor="#866cff" stopOpacity="0"/></linearGradient></defs><path d="M0 200 C60 196 75 169 123 177 S182 130 232 149 S310 100 353 117 S422 70 466 91 S541 48 583 66 S650 20 700 33 L700 230 L0 230Z" fill="url(#fill)"/><path d="M0 200 C60 196 75 169 123 177 S182 130 232 149 S310 100 353 117 S422 70 466 91 S541 48 583 66 S650 20 700 33" fill="none" stroke="#8b70ff" strokeWidth="4"/></svg><div className="chart-dates"><span>20 Juil.</span><span>27 Juil.</span><span>3 Août</span><span>10 Août</span><span>17 Août</span></div></div>}

function Campaigns({data,filter,setFilter,open,notify}:{data:typeof baseCampaigns;filter:string;setFilter:(x:string)=>void;open:()=>void;notify:(x:string)=>void}){const[view,setView]=useState("grid");return <div className="app-page"><div className="page-toolbar"><div className="filter-tabs">{["Toutes","Active","Review","Brouillon"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div><button className="tool-btn" onClick={()=>setView(view==="grid"?"list":"grid")}>{view==="grid"?"☷ Grille":"☰ Liste"}</button><button className="accent-btn" onClick={open}>＋ Créer</button></div></div>{data.length===0?<Empty icon="◉" title="Aucune campagne" text="Aucune campagne ne correspond à ce filtre." action="Créer une campagne" onClick={open}/>:<div className={`campaign-grid ${view}`}>{data.map(c=><article className="campaign-card" key={c.name}><div className="campaign-card-top"><b className={c.color}>{c.initials}</b><Badge tone={c.status==="Review"?"amber":c.status==="Brouillon"?"gray":"green"}>{c.status}</Badge><button>•••</button></div><h3>{c.name}</h3><p>Clipping organique · Août 2026</p><div className="campaign-kpis"><span><small>CLIPS</small><b>{c.clips}</b></span><span><small>VUES</small><b>{c.views}</b></span><span><small>BUDGET</small><b>{c.budget.toLocaleString("fr-FR")} €</b></span></div><div className="budget-row"><span>Budget consommé</span><b>{c.progress}%</b></div><div className="progress"><i style={{width:`${c.progress}%`}}/></div><footer><div className="stacked"><i>ML</i><i>NB</i><i>+2</i></div><button onClick={()=>notify(`${c.name} ouverte`)}>Ouvrir →</button></footer></article>)}</div>}</div>}

function Studio({notify,openUpload}:{notify:(x:string)=>void;openUpload:()=>void}){const[tab,setTab]=useState("Moments forts");const[processing,setProcessing]=useState(false);const run=()=>{setProcessing(true);setTimeout(()=>{setProcessing(false);notify("Analyse terminée : 8 moments détectés")},1800)};return <div className="app-page"><div className="studio-hero"><div><Badge tone="purple">CLIPSCALE AI</Badge><h2>Une heure de contenu.<br/><em>10 clips prêts à performer.</em></h2><p>Importez une vidéo ou collez un lien. Notre moteur détecte les moments forts, écrit les hooks et prépare le montage.</p><div><button className="accent-btn" onClick={openUpload}>⇧ Importer une vidéo</button><button className="tool-btn" onClick={run}>⌁ Coller un lien</button></div></div><div className={`ai-orb ${processing?"processing":""}`}><i/><i/><b>✦</b><span>{processing?"Analyse...":"IA prête"}</span></div></div><div className="studio-tabs">{["Moments forts","Hooks","Sous-titres","Brand kit","Exports"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"active":""} key={x}>{x}</button>)}</div><div className="ai-grid"><article className="app-card source-card"><div className="video-placeholder"><span>▶</span><small>48:26</small></div><h3>Podcast — Construire une audience</h3><p>Nova Finance · Importé il y a 12 min</p><div className="source-actions"><button onClick={run}>{processing?"Analyse en cours…":"✦ Analyser avec l’IA"}</button><button>•••</button></div></article><article className="app-card moments"><div className="app-card-head"><div><small>{tab.toUpperCase()}</small><h3>Suggestions de l’IA</h3></div><Badge tone="purple">8 trouvés</Badge></div>{[["02:14 — 02:58","Le déclic que personne n’attend","94"],["08:31 — 09:16","La méthode en 3 étapes","89"],["21:04 — 21:47","Cette erreur coûte des milliers","86"],["36:18 — 37:02","Le conseil le plus sous-coté","82"]].map((m,i)=><div className="moment-row" key={m[0]}><button>▶</button><span><small>{m[0]}</small><strong>{m[1]}</strong><i><b style={{width:`${Number(m[2])}%`}}/></i></span><em>{m[2]}<small>score</small></em><button onClick={()=>notify("Clip ajouté au pipeline")}>＋</button></div>)}</article></div></div>}

function Clips({notify}:{notify:(x:string)=>void}){const[status,setStatus]=useState("Tous");const[list,setList]=useState(clipData);const approve=(title:string)=>{setList(v=>v.map(x=>x.title===title?{...x,status:"Approuvé"}:x));notify("Clip approuvé et prêt à planifier")};return <div className="app-page"><div className="page-toolbar"><div className="filter-tabs">{["Tous","Brief","Montage","Validation","Approuvé","Publié"].map(x=><button key={x} className={status===x?"active":""} onClick={()=>setStatus(x)}>{x}</button>)}</div><button className="tool-btn">⇅ Trier</button></div><div className="clips-board">{["Brief","Montage","Validation","Publié"].map(col=><section key={col}><header><span>{col}</span><b>{list.filter(x=>x.status===col||(col==="Publié"&&["Viral","Publié","Approuvé"].includes(x.status))).length}</b><button>＋</button></header>{list.filter(x=>x.status===col||(col==="Publié"&&["Viral","Publié","Approuvé"].includes(x.status))).map((c,i)=><article className="clip-card" key={c.title}><div className={`clip-thumb ${c.tone}`}><i>▶</i><span>0:{42+i*5}</span><Badge tone={c.score>90?"purple":"green"}>IA {c.score}</Badge></div><small>{c.client}</small><h3>{c.title}</h3><div className="clip-stats"><span>{c.views} vues</span><span>{c.retention||"—"}% rétention</span></div><footer><div className="stacked"><i>ML</i><i>AV</i></div>{col==="Validation"?<button onClick={()=>approve(c.title)}>✓ Approuver</button>:<button>•••</button>}</footer></article>)}</section>)}</div></div>}

function Calendar({notify}:{notify:(x:string)=>void}){const days=["Lun. 17","Mar. 18","Mer. 19","Jeu. 20","Ven. 21","Sam. 22","Dim. 23"];const events=[{d:0,t:"09:30",n:"Le déclic qui…",p:"TikTok",c:"purple"},{d:1,t:"12:00",n:"3 erreurs qui…",p:"Reels",c:"pink"},{d:2,t:"18:30",n:"La règle des…",p:"Shorts",c:"red"},{d:3,t:"11:15",n:"Pourquoi personne…",p:"TikTok",c:"blue"},{d:4,t:"17:00",n:"Ce conseil vaut…",p:"Reels",c:"green"}];return <div className="app-page"><div className="page-toolbar"><div><button className="tool-btn">‹</button><button className="tool-btn">Cette semaine</button><button className="tool-btn">›</button></div><div><button className="tool-btn">Semaine ⌄</button><button className="accent-btn" onClick={()=>notify("Créneau de publication ajouté")}>＋ Planifier</button></div></div><div className="calendar"><div className="cal-header">{days.map((d,i)=><div className={i===1?"today":""} key={d}><span>{d.split(" ")[0]}</span><b>{d.split(" ")[1]}</b></div>)}</div><div className="cal-body">{days.map((_,d)=><div key={d}>{events.filter(e=>e.d===d).map(e=><article className={e.c} key={e.n}><small>{e.t}</small><strong>{e.n}</strong><span>{e.p}</span></article>)}{d>4&&<button onClick={()=>notify("Nouveau créneau sélectionné")}>＋</button>}</div>)}</div></div><div className="schedule-summary">{[["18","Planifiés"],["3","En attente"],["4","Comptes connectés"],["19:15","Meilleur horaire"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div>}

function Team({notify,invite}:{notify:(x:string)=>void;invite:()=>void}){return <div className="app-page"><div className="page-toolbar"><div className="filter-tabs"><button className="active">Tous les membres</button><button>Monteurs</button><button>Managers</button></div><button className="accent-btn" onClick={invite}>＋ Inviter</button></div><div className="team-metrics">{[["4","Membres actifs"],["33","Clips cette semaine"],["89%","Taux de validation"],["4.2 h","Délai moyen"]].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div><div className="app-card team-table"><div className="app-card-head"><div><small>ÉQUIPE</small><h3>Performance et charge</h3></div><button>Exporter ↗</button></div>{team.map((m,i)=><div className="team-row" key={m[1]}><b className={["violet","cyan","orange","green"][i]}>{m[0]}</b><span><strong>{m[1]}</strong><small>{m[2]}</small></span><em>{m[3]}<small>cette semaine</small></em><div><i><b style={{width:m[4]}}/></i><small>{m[4]} qualité</small></div><Badge tone={i===2?"amber":"green"}>{i===2?"Chargé":"Disponible"}</Badge><button onClick={()=>notify(`Profil de ${m[1]} ouvert`)}>•••</button></div>)}</div><div className="leaderboard"><article className="app-card"><h3>🏆 Classement du mois</h3>{team.slice(0,3).map((m,i)=><div key={m[1]}><b>#{i+1}</b><span>{m[1]}</span><em>{[482,376,291][i]}K vues</em></div>)}</article><article className="app-card"><h3>Charge de travail</h3><div className="workload">{team.map((m,i)=><span key={m[1]}><b>{m[0]}</b><i style={{height:`${[78,64,92,51][i]}%`}}/><small>{[78,64,92,51][i]}%</small></span>)}</div></article></div></div>}

function Clients({notify,add}:{notify:(x:string)=>void;add:()=>void}){return <div className="app-page"><div className="page-toolbar"><div className="client-search">⌕ <input placeholder="Rechercher un client..."/></div><button className="accent-btn" onClick={add}>＋ Ajouter un client</button></div><div className="client-grid">{clients.map((c,i)=><article className="client-card" key={c[1]}><header><b className={["violet","cyan","orange","green"][i]}>{c[0]}</b><Badge tone={i===3?"gray":"green"}>{i===3?"Onboarding":"Actif"}</Badge><button>•••</button></header><h3>{c[1]}</h3><p>{c[2]}</p><div><span><small>CLIPS</small><b>{c[3]}</b></span><span><small>VUES</small><b>{c[4]}</b></span></div><footer><div className="stacked"><i>AV</i><i>ML</i></div><button onClick={()=>notify(`Portail ${c[1]} ouvert`)}>Ouvrir le portail →</button></footer></article>)}</div><article className="app-card client-portal"><div><Badge tone="purple">PORTAIL MARQUE BLANCHE</Badge><h2>Offrez à vos clients une expérience premium.</h2><p>Validation des clips, commentaires, analytics et factures dans un portail à votre image.</p><button className="accent-btn" onClick={()=>notify("Aperçu du portail généré")}>Prévisualiser le portail</button></div><div className="portal-mock"><span/><span/><span/><div/></div></article></div>}

function Marketplace({notify}:{notify:(x:string)=>void}){const jobs=[["Higgs AI","Clips UGC IA","3,00 €","/ 1K vues","12K €"],["Mindset Club","Podcast business","2,20 €","/ 1K vues","8K €"],["Nova Music","Lancement single","1,50 €","/ 1K vues","25K €"],["Zenith Sport","Highlights fitness","2,80 €","/ 1K vues","10K €"]];return <div className="app-page"><div className="market-hero"><div><Badge tone="purple">MARKETPLACE</Badge><h2>Les meilleures campagnes.<br/>Les meilleurs clippeurs.</h2><p>Recrutez au résultat ou trouvez des campagnes à fort potentiel.</p></div><div className="market-stats"><span><b>1 240</b><small>Clippeurs vérifiés</small></span><span><b>84K €</b><small>Budgets actifs</small></span></div></div><div className="page-toolbar"><div className="filter-tabs"><button className="active">Tendances</button><button>Nouvelles</button><button>CPM élevé</button><button>Mes favoris</button></div><button className="tool-btn">Filtres ⚙</button></div><div className="job-grid">{jobs.map((j,i)=><article className="job-card" key={j[0]}><header><b className={["violet","cyan","pink","green"][i]}>{j[0].slice(0,2)}</b><Badge tone={i===2?"amber":"green"}>{i===2?"Musique":"Business"}</Badge><button>♡</button></header><small>{j[0]}</small><h3>{j[1]}</h3><div className="cpm"><b>{j[2]}</b><span>{j[3]}</span></div><p>Budget restant <strong>{j[4]}</strong></p><div className="progress"><i style={{width:`${[68,42,81,55][i]}%`}}/></div><footer><span>{[128,67,241,94][i]} participants</span><button onClick={()=>notify(`Candidature envoyée à ${j[0]}`)}>Postuler →</button></footer></article>)}</div></div>}

function Finance({notify}:{notify:(x:string)=>void}){return <div className="app-page"><div className="wallet-card"><div><small>SOLDE DISPONIBLE</small><h2>12 840,50 €</h2><p>+ 4 286 € ce mois-ci</p></div><div><button className="accent-btn" onClick={()=>notify("Demande de retrait préparée")}>↗ Retirer</button><button className="tool-btn">＋ Ajouter des fonds</button></div></div><div className="finance-metrics">{[["CA DU MOIS","18 420 €","↗ 31.5%"],["PAIEMENTS CLIPPEURS","4 280 €","↗ 18.2%"],["MARGE NETTE","76.8%","↗ 4.1%"],["À FACTURER","6 740 €","12 factures"]].map(x=><article className="app-card" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><div className="finance-grid"><article className="app-card"><div className="app-card-head"><div><small>TRANSACTIONS</small><h3>Activité récente</h3></div><button>Tout voir →</button></div>{[["↓","Paiement Nova Finance","+ 2 760 €","Aujourd’hui"],["↑","Paiement Maya Laurent","− 420 €","Aujourd’hui"],["↓","Paiement Kinetik Podcast","+ 1 023 €","Hier"],["↑","Paiement Nassim B.","− 286 €","Hier"]].map((t,i)=><div className="transaction" key={t[1]}><b className={i%2?"out":"in"}>{t[0]}</b><span><strong>{t[1]}</strong><small>{t[3]}</small></span><em className={i%2?"":"positive"}>{t[2]}</em></div>)}</article><article className="app-card margin-card"><div className="app-card-head"><div><small>RENTABILITÉ</small><h3>Marge par client</h3></div></div>{baseCampaigns.slice(0,3).map((c,i)=><div key={c.name}><span>{c.name}</span><b>{[82,74,69][i]}%</b><i><em style={{width:`${[82,74,69][i]}%`}}/></i></div>)}</article></div><div className="app-card invoice-table"><div className="app-card-head"><div><small>FACTURATION</small><h3>Factures récentes</h3></div><button onClick={()=>notify("Facture créée en brouillon")}>＋ Nouvelle facture</button></div>{[["#CS-0826","Nova Finance","2 760 €","Payée"],["#CS-0825","Kinetik Podcast","1 023 €","Payée"],["#CS-0824","Maison Aura","586 €","En attente"]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><em>{x[2]}</em><Badge tone={i===2?"amber":"green"}>{x[3]}</Badge><button>•••</button></div>)}</div></div>}

function Analytics({range,setRange,notify}:{range:string;setRange:(x:string)=>void;notify:(x:string)=>void}){const[metric,setMetric]=useState("Vues");return <div className="app-page"><div className="page-toolbar"><div className="filter-tabs">{["Vues","Rétention","Leads","Revenus"].map(x=><button className={metric===x?"active":""} onClick={()=>setMetric(x)} key={x}>{x}</button>)}</div><div><select className="tool-btn" value={range} onChange={e=>setRange(e.target.value)}><option>7 jours</option><option>30 jours</option><option>90 jours</option></select><button className="accent-btn" onClick={()=>notify("Rapport exporté et lien copié")}>↗ Exporter le rapport</button></div></div><div className="analytics-hero app-card"><div className="app-card-head"><div><small>ÉVOLUTION DES {metric.toUpperCase()}</small><h3>Performance multiréseaux</h3></div><div className="legend"><span><i className="purple"/>Cette période</span><span><i/>Période précédente</span></div></div><AreaChart/></div><div className="analytics-grid"><article className="app-card"><div className="app-card-head"><div><small>FUNNEL</small><h3>Des vues aux ventes</h3></div></div>{[["Vues","2.91M","100%"],["Visites profil","184K","6.3%"],["Leads","4 820","2.6%"],["Ventes","286","5.9%"]].map((x,i)=><div className="funnel-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><i style={{width:`${100-i*22}%`}}/><em>{x[2]}</em></div>)}</article><article className="app-card"><div className="app-card-head"><div><small>TOP CONTENU</small><h3>Clips les plus rentables</h3></div></div>{clipData.slice(0,4).map((c,i)=><div className="rank-row" key={c.title}><b>#{i+1}</b><span><strong>{c.title}</strong><small>{c.client}</small></span><em>{c.views}<small>{[1240,860,620,418][i]} €</small></em></div>)}</article><article className="app-card geo-card"><div className="app-card-head"><div><small>AUDIENCE</small><h3>Pays principaux</h3></div></div>{[["France",61],["Belgique",14],["Suisse",9],["Canada",7]].map(x=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:`${x[1]}%`}}/></i><em>{x[1]}%</em></div>)}</article></div></div>}

function Automations({values,setValues,notify}:{values:boolean[];setValues:(v:boolean[])=>void;notify:(x:string)=>void}){const items=[["✦","Analyser chaque nouveau rush","Lance automatiquement l’IA après un import."],["✓","Notifier le client à la validation","Envoie un email lorsqu’un clip est prêt."],["↗","Publier après approbation","Ajoute le clip au prochain créneau disponible."],["€","Calculer les paiements au CPM","Met à jour les gains chaque nuit."],["♙","Assigner selon la charge","Choisit automatiquement le monteur disponible."]];const toggle=(i:number)=>{setValues(values.map((x,j)=>j===i?!x:x));notify(values[i]?"Automation désactivée":"Automation activée")};return <div className="app-page"><div className="automation-hero"><div><Badge tone="purple">NO-CODE</Badge><h2>Votre agence travaille<br/>même quand vous dormez.</h2><p>Automatisez les tâches répétitives en quelques clics.</p></div><button className="accent-btn" onClick={()=>notify("Nouvelle automation créée")}>＋ Créer une automation</button></div><div className="automation-list">{items.map((a,i)=><article className="app-card" key={a[1]}><b>{a[0]}</b><span><strong>{a[1]}</strong><small>{a[2]}</small></span><em><small>{values[i]?"ACTIVE":"INACTIVE"}</small><button className={values[i]?"on":""} onClick={()=>toggle(i)}><i/></button></em></article>)}</div><div className="recipes"><h3>Recettes recommandées</h3><div>{[["Google Drive","Nouveau fichier → Créer un projet","＋"],["Slack","Clip approuvé → Notifier l’équipe","＋"],["Stripe","Facture payée → Créditer le wallet","＋"]].map(x=><article className="app-card" key={x[0]}><b>{x[0].slice(0,2)}</b><span><small>{x[0]}</small><strong>{x[1]}</strong></span><button onClick={()=>notify("Recette ajoutée")}>{x[2]}</button></article>)}</div></div></div>}

function Integrations({connected,connect}:{connected:string[];connect:(x:string)=>void}){const apps=[["Google Drive","Import automatique des rushs","GD"],["Dropbox","Synchronisation de dossiers","DB"],["Discord","Notifications et briefs","DC"],["Slack","Alertes de production","SL"],["TikTok","Publication et analytics","TK"],["Instagram","Reels et statistiques","IG"],["YouTube","Shorts et analytics","YT"],["Stripe","Paiements et factures","ST"],["Notion","Synchronisation des briefs","NT"],["Zapier","5 000+ applications","ZP"]];return <div className="app-page"><div className="integration-head"><div><h2>Connectez votre stack.</h2><p>ClipScale devient le centre de votre écosystème.</p></div><div className="client-search">⌕ <input placeholder="Rechercher une intégration..."/></div></div><div className="integration-grid">{apps.map((a,i)=><article className="app-card" key={a[0]}><b className={["gd","db","dc","sl","tk","ig","yt","st","nt","zp"][i]}>{a[2]}</b><span><strong>{a[0]}</strong><small>{a[1]}</small></span><button className={connected.includes(a[0])?"connected":""} onClick={()=>connect(a[0])}>{connected.includes(a[0])?"✓ Connecté":"Connecter"}</button></article>)}</div><div className="api-banner"><div><Badge tone="purple">DEVELOPER</Badge><h3>Construisez avec l’API ClipScale.</h3><p>Webhooks, clés API et documentation complète.</p></div><button>Voir la documentation →</button></div></div>}

function Settings({compact,setCompact,notify,showFeatures}:{compact:boolean;setCompact:(v:boolean)=>void;notify:(x:string)=>void;showFeatures:()=>void}){const[toggles,setToggles]=useState([true,true,false,true]);return <div className="app-page settings-layout"><nav>{["Général","Workspace","Branding","Notifications","Sécurité","API & Webhooks"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</nav><section><div className="settings-title"><h2>Paramètres généraux</h2><p>Personnalisez votre expérience ClipScale.</p></div><div className="settings-card"><h3>Profil de l’agence</h3><label>Nom de l’agence<input defaultValue="Ventura Agency"/></label><div className="settings-two"><label>Email de contact<input defaultValue="hello@ventura-agency.fr"/></label><label>Site web<input defaultValue="ventura-agency.fr"/></label></div><label>Devise<select defaultValue="EUR"><option>EUR — Euro</option><option>USD — Dollar</option><option>CHF — Franc suisse</option></select></label><button className="accent-btn" onClick={()=>notify("Modifications enregistrées")}>Enregistrer</button></div><div className="settings-card"><h3>Interface</h3><div className="setting-row"><span><strong>Mode compact</strong><small>Réduit les espacements du tableau de bord.</small></span><button className={compact?"switch on":"switch"} onClick={()=>setCompact(!compact)}><i/></button></div><div className="setting-row"><span><strong>Langue</strong><small>Langue de l’interface et des emails.</small></span><select><option>Français</option><option>English</option></select></div><div className="setting-row"><span><strong>Fuseau horaire</strong><small>Utilisé pour toutes les programmations.</small></span><select><option>Europe/Paris</option><option>Europe/Zurich</option></select></div></div><div className="settings-card"><h3>Centre produit</h3><p className="setting-copy">Explorez un catalogue structuré de 1 000 fonctionnalités, améliorations et connexions produit.</p><button className="tool-btn" onClick={showFeatures}>Explorer les 1 000 éléments →</button></div></section></div>}

function Modal({type,close,search,setSearch,results,createCampaign,go,notify,onboard,setOnboard}:{type:string;close:()=>void;search:string;setSearch:(x:string)=>void;results:Feature[];createCampaign:(e:React.FormEvent<HTMLFormElement>)=>void;go:(x:string)=>void;notify:(x:string)=>void;onboard:number;setOnboard:(x:number)=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={`app-modal ${type==="features"?"wide":""}`}><button className="modal-close" onClick={close}>×</button>{type==="campaign"&&<><Badge tone="purple">NOUVELLE CAMPAGNE</Badge><h2>Lancez votre prochaine campagne.</h2><p>Définissez les bases. Vous pourrez tout modifier ensuite.</p><form onSubmit={createCampaign}><label>Nom de la campagne<input required name="name" placeholder="Ex. Lancement Podcast Août"/></label><div className="form-two"><label>Client<select><option>Nova Finance</option><option>Kinetik Podcast</option><option>Maison Aura</option></select></label><label>Budget total<input name="budget" type="number" defaultValue="2500"/></label></div><div className="form-two"><label>CPM<input type="number" step=".1" defaultValue="2.5"/></label><label>Plateformes<select><option>Toutes les plateformes</option><option>TikTok uniquement</option><option>Reels + Shorts</option></select></label></div><div className="form-actions"><button type="button" onClick={close}>Annuler</button><button className="accent-btn">Créer la campagne →</button></div></form></>}
 {type==="search"&&<><div className="command-input">⌕<input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une fonctionnalité ou une page..."/><kbd>ESC</kbd></div><div className="command-results">{search?results.map(r=><button key={r.name} onClick={()=>{go(r.group==="Pilotage"?"Vue d’ensemble":r.group);close()}}><b>{r.icon}</b><span><strong>{r.name}</strong><small>{r.group}</small></span><em>↵</em></button>):<><small>ACCÈS RAPIDE</small>{["Campagnes","Studio IA","Marketplace","Analytics"].map(x=><button key={x} onClick={()=>{go(x);close()}}><b>→</b><span><strong>{x}</strong><small>Ouvrir la page</small></span></button>)}</>}</div></>}
 {type==="upload"&&<><Badge tone="purple">IMPORT</Badge><h2>Ajoutez votre contenu source.</h2><div className="drop-zone" onClick={()=>notify("Sélecteur de fichier prêt")}><b>⇧</b><strong>Déposez votre vidéo ici</strong><span>MP4, MOV, MP3 ou WAV · 10 Go maximum</span><button>Choisir un fichier</button></div><div className="or"><span/>OU<span/></div><label>Lien YouTube, Drive ou Dropbox<input placeholder="https://..."/></label><div className="form-actions"><button onClick={close}>Annuler</button><button className="accent-btn" onClick={()=>{notify("Import ajouté à la file d’analyse");close()}}>Importer et analyser →</button></div></>}
 {type==="client"&&<><Badge tone="purple">NOUVEAU CLIENT</Badge><h2>Créez un espace client.</h2><form onSubmit={e=>{e.preventDefault();notify("Client ajouté et invitation envoyée");close()}}><label>Nom de l’entreprise<input required placeholder="Nom du client"/></label><label>Email du contact<input required type="email" placeholder="contact@entreprise.fr"/></label><div className="form-two"><label>Forfait<select><option>Agency — 30 clips</option><option>Starter — 12 clips</option><option>Sur mesure</option></select></label><label>Prix mensuel<input type="number" defaultValue="1500"/></label></div><div className="form-actions"><button type="button" onClick={close}>Annuler</button><button className="accent-btn">Créer et inviter →</button></div></form></>}
 {type==="invite"&&<><Badge tone="purple">ÉQUIPE</Badge><h2>Invitez un nouveau membre.</h2><form onSubmit={e=>{e.preventDefault();notify("Invitation envoyée");close()}}><label>Adresse email<input required type="email" placeholder="membre@email.fr"/></label><label>Rôle<select><option>Monteur</option><option>Content manager</option><option>Administrateur</option><option>Client</option></select></label><label className="checkbox"><input type="checkbox" defaultChecked/> Envoyer le guide d’onboarding</label><div className="form-actions"><button type="button" onClick={close}>Annuler</button><button className="accent-btn">Envoyer l’invitation →</button></div></form></>}
 {type==="features"&&<><Badge tone="purple">PRODUCT UNIVERSE</Badge><h2>1 000 fonctionnalités et améliorations.</h2><p>Un catalogue transparent : disponible, prototype ou connexion externe à activer.</p><FeatureUniverse/></>}
 {type==="tour"&&<><Badge tone="purple">ONBOARDING</Badge><h2>Configurez votre agence.</h2><p>{onboard}% terminé · encore quelques minutes.</p><div className="tour-list">{[["✓","Créer votre workspace",true],["✓","Ajouter votre premier client",true],["3","Connecter un réseau social",onboard>70],["4","Inviter un monteur",onboard>85],["5","Lancer une campagne",onboard===100]].map((x,i)=><button key={String(x[1])} onClick={()=>{setOnboard(Math.min(100,onboard+12));notify("Étape terminée")}} className={x[2]?"done":""}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]?"Terminé":"À compléter"}</small></span><em>→</em></button>)}</div></>}</div></div>}
