"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";

type Offer={id:string;title:string;clientName:string;description:string;platforms:string;budgetCents:number;cpmCents:number;applicationCount:number;createdAt:number};
type Me={authenticated:boolean;user?:{displayName:string;email:string};profile?:{displayName:string;bio:string;skills:string;portfolioUrl:string}|null;offers?:Array<{id:string;title:string;status:string}>;applications?:Array<{id:string;title:string;clientName:string;status:string}>;received?:Array<{id:string;title:string;displayName:string|null;skills:string|null;message:string;portfolioUrl:string;status:string}>;signIn?:string};
const money=(cents:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(cents/100);

export default function MarketplaceLive(){
 const[offers,setOffers]=useState<Offer[]>([]),[me,setMe]=useState<Me>({authenticated:false}),[loading,setLoading]=useState(true),[tab,setTab]=useState("missions"),[selected,setSelected]=useState<Offer|null>(null),[notice,setNotice]=useState("");
 const authHeaders=useCallback(async():Promise<Record<string,string>>=>{const{data}=await supabase.auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}},[]);
 const load=useCallback(async()=>{setLoading(true);const headers=await authHeaders();const [market,mine]=await Promise.all([fetch("/api/marketplace",{cache:"no-store"}),fetch("/api/me",{headers,cache:"no-store"})]);const marketData=await market.json();setOffers(marketData.offers||[]);const meData=await mine.json();setMe(mine.ok?meData:{authenticated:false});setLoading(false)},[authHeaders]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(()=>{setNotice("Impossible de charger la marketplace.");setLoading(false)}),0);return()=>window.clearTimeout(timer)},[load]);
 const submit=async(url:string,data:Record<string,FormDataEntryValue>,form:HTMLFormElement)=>{setNotice("");const headers=await authHeaders();if(!("Authorization" in headers)){setNotice("Connectez-vous avec votre compte ClipScale pour continuer.");return}const response=await fetch(url,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){setNotice(result.error||"Une erreur est survenue.");return}form.reset();setSelected(null);setNotice(url.includes("offers")?"Mission publiée avec succès.":"Candidature envoyée avec succès.");await load()};
 const publish=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;submit("/api/offers",Object.fromEntries(new FormData(f)),f)};
 const apply=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;submit("/api/applications",{...Object.fromEntries(new FormData(f)),offerId:selected?.id||""},f)};
 const decide=async(id:string,status:"accepted"|"rejected")=>{const headers=await authHeaders();const response=await fetch(`/api/applications/${id}`,{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({status})});const result=await response.json();if(!response.ok){setNotice(result.error||"Décision impossible.");return}setNotice(status==="accepted"?"Clippeur sélectionné.":"Candidature refusée.");await load()};
 return <main className="live-market">
  <div className="market-bg"><i/><i/><i/></div>
  <header className="live-nav"><Link href="/" className="live-brand"><span>{"///"}</span> ClipScale <small>MARKETPLACE</small></Link><nav><button onClick={()=>setTab("missions")} className={tab==="missions"?"active":""}>Missions</button><button onClick={()=>setTab("publier")} className={tab==="publier"?"active":""}>Publier</button><button onClick={()=>setTab("activite")} className={tab==="activite"?"active":""}>Mon activité</button></nav>{me.authenticated?<div className="user-pill"><i/>{me.user?.displayName}</div>:<Link className="signin" href="/">Se connecter à ClipScale</Link>}</header>
  <section className="market-hero"><span>MARKETPLACE V1 · DONNÉES EN DIRECT</span><h1>Les créateurs publient.<br/><em>Les clippeurs performent.</em></h1><p>Des missions, des candidatures attribuées et un historique centralisé dans votre espace.</p><div><b>{offers.length}</b><small>missions ouvertes</small><b>{offers.reduce((s,o)=>s+Number(o.applicationCount),0)}</b><small>candidatures</small></div></section>
  {notice&&<div className="market-notice" role="status">✓ {notice}</div>}
  {tab==="missions"&&<section className="market-content"><div className="market-title"><div><span>MISSIONS OUVERTES</span><h2>Trouvez votre prochaine campagne.</h2></div><button onClick={()=>setTab("publier")}>＋ Publier une mission</button></div>{loading?<div className="market-empty">Chargement des missions…</div>:offers.length===0?<div className="market-empty"><i>◎</i><h3>Aucune mission publiée pour le moment.</h3><p>Soyez la première agence à publier une offre réelle sur ClipScale.</p><button onClick={()=>setTab("publier")}>Publier la première mission</button></div>:<div className="live-offers">{offers.map(o=><article key={o.id}><header><span>OUVERTE</span><small>{new Date(o.createdAt).toLocaleDateString("fr-FR")}</small></header><h3>{o.title}</h3><p className="client">{o.clientName}</p><p>{o.description}</p><div className="tags">{o.platforms.split(",").map(x=><span key={x}>{x.trim()}</span>)}</div><div className="offer-numbers"><span><small>BUDGET</small><b>{money(o.budgetCents)}</b></span><span><small>CPM</small><b>{o.cpmCents?money(o.cpmCents):"Fixe"}</b></span><span><small>CANDIDATS</small><b>{o.applicationCount}</b></span></div><button onClick={()=>{setSelected(o);setNotice("")}}>Candidater →</button></article>)}</div>}</section>}
  {tab==="publier"&&<section className="market-form-wrap"><div><span>POUR LES AGENCES</span><h2>Publiez une mission claire.</h2><p>Elle devient immédiatement visible par les clippeurs. La publication nécessite une connexion.</p></div><form onSubmit={publish}><label>Titre de la mission<input name="title" required minLength={5} maxLength={90} placeholder="Ex. 30 clips business par mois"/></label><div><label>Client ou marque<input name="clientName" required maxLength={70} placeholder="Nom public affiché"/></label><label>Plateformes<input name="platforms" required placeholder="TikTok, Reels, Shorts"/></label></div><label>Description<textarea name="description" required minLength={30} maxLength={1200} placeholder="Décrivez le contenu source, le style recherché, le rythme et les livrables…"/></label><div><label>Budget total (€)<input name="budget" required type="number" min="10" step="1" placeholder="1500"/></label><label>CPM optionnel (€)<input name="cpm" type="number" min="0" step="0.1" placeholder="2.50"/></label></div><button>Publier la mission →</button><small>Vous pourrez gérer les candidatures depuis « Mon activité ».</small></form></section>}
  {tab==="activite"&&<section className="market-content"><div className="market-title"><div><span>VOTRE ESPACE</span><h2>Offres et candidatures.</h2></div>{!me.authenticated&&<Link className="signin" href="/">Se connecter avec ClipScale</Link>}</div>{me.authenticated?<div className="activity-grid"><article><h3>Mes missions</h3>{me.offers?.length?me.offers.map(x=><div key={x.id}><span>{x.title}</span><b>{x.status}</b></div>):<p>Aucune mission publiée.</p>}</article><article><h3>Mes candidatures</h3>{me.applications?.length?me.applications.map(x=><div key={x.id}><span>{x.title}<small>{x.clientName}</small></span><b>{x.status}</b></div>):<p>Aucune candidature envoyée.</p>}</article><article className="received"><h3>Candidatures reçues</h3>{me.received?.length?me.received.map(x=><div className="candidate" key={x.id}><span><strong>{x.displayName||"Clippeur"}</strong><small>{x.title} · {x.skills||"Spécialités non indiquées"}</small><p>{x.message}</p>{x.portfolioUrl&&<a href={x.portfolioUrl} target="_blank" rel="noreferrer">Voir le portfolio ↗</a>}</span><em className={x.status}>{x.status}</em>{x.status==="pending"&&<aside><button onClick={()=>decide(x.id,"accepted")}>Sélectionner</button><button onClick={()=>decide(x.id,"rejected")}>Refuser</button></aside>}</div>):<p>Aucune candidature reçue.</p>}</article></div>:<div className="market-empty"><i>♙</i><h3>Connectez-vous pour retrouver votre activité.</h3><p>Vos offres, votre profil et vos candidatures sont associés à votre compte.</p></div>}</section>}
  {selected&&<div className="apply-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><form className="apply-modal" onSubmit={apply}><button type="button" className="apply-close" onClick={()=>setSelected(null)}>×</button><span>CANDIDATURE</span><h2>{selected.title}</h2><p>{selected.clientName} · {money(selected.budgetCents)}</p><label>Votre nom public<input name="displayName" defaultValue={me.profile?.displayName||me.user?.displayName||""} required/></label><label>Vos spécialités<input name="skills" defaultValue={me.profile?.skills||""} placeholder="Podcast, business, sous-titres…" required/></label><label>Présentation<textarea name="bio" defaultValue={me.profile?.bio||""} minLength={20} required placeholder="Votre expérience et votre façon de travailler…"/></label><label>Lien portfolio<input name="portfolioUrl" type="url" defaultValue={me.profile?.portfolioUrl||""} placeholder="https://…"/></label><label>Message à l’agence<textarea name="message" minLength={20} required placeholder="Expliquez pourquoi vous correspondez à cette mission…"/></label><button>Envoyer ma candidature →</button></form></div>}
 </main>
}
